// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9-wx2v-MKVe5Ah_fvPr-rZ6IVO1I5mUM',
    appId: '1:921761295244:web:47c637c7a3387d043b44a9',
    messagingSenderId: '921761295244',
    projectId: 'cleansl-8f833',
    authDomain: 'cleansl-8f833.firebaseapp.com',
    storageBucket: 'cleansl-8f833.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVEGHui1YGCAjNQJHvFXrRC5FKc52LTfo',
    appId: '1:921761295244:android:02c5a80d216f3f653b44a9',
    messagingSenderId: '921761295244',
    projectId: 'cleansl-8f833',
    storageBucket: 'cleansl-8f833.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7GxoqRBuPHrJ0b855kH1ZulouE_VyMsE',
    appId: '1:921761295244:ios:e984197cea51c6863b44a9',
    messagingSenderId: '921761295244',
    projectId: 'cleansl-8f833',
    storageBucket: 'cleansl-8f833.firebasestorage.app',
    iosBundleId: 'com.example.cleanslApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7GxoqRBuPHrJ0b855kH1ZulouE_VyMsE',
    appId: '1:921761295244:ios:e984197cea51c6863b44a9',
    messagingSenderId: '921761295244',
    projectId: 'cleansl-8f833',
    storageBucket: 'cleansl-8f833.firebasestorage.app',
    iosBundleId: 'com.example.cleanslApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9-wx2v-MKVe5Ah_fvPr-rZ6IVO1I5mUM',
    appId: '1:921761295244:web:9e8d7dd883d916283b44a9',
    messagingSenderId: '921761295244',
    projectId: 'cleansl-8f833',
    authDomain: 'cleansl-8f833.firebaseapp.com',
    storageBucket: 'cleansl-8f833.firebasestorage.app',
  );
}
